### ISSUE TITLE
Backup fails if BGSAVE is in progress

### ISSUE THREAD

**Issue by philipcristiano** [josegonzalez/ruby-redis-backup#2]
```
/var/lib/gems/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:85:in `call': ERR Background save already in progress (Redis::CommandError)
        from /var/lib/gems/1.9.1/gems/redis-3.0.2/lib/redis.rb:120:in `block in bgsave'
        from /var/lib/gems/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `block in synchronize'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.0.2/lib/redis.rb:119:in `bgsave'
        from /var/lib/gems/1.9.1/gems/redis-backup-0.0.3/bin/redis-backup:63:in `<top (required)>'
        from /usr/local/bin/redis-backup:23:in `load'
        from /usr/local/bin/redis-backup:23:in `<main>'
```

**Comment by josegonzalez** [comment]
Ok

**Comment by josegonzalez** [comment]
This package is no longer maintained, though if someone wants to contribute a patch for this, I'd be happy to merge it.
